// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client"

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type BlogPostDocumentDataSlicesSlice =
  | CalloutSlice
  | HeroSlice
  | BlogPostBodySlice

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Title (Browser Tab Title) field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Card Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.card_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  card_image: prismic.ImageField<never>

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >

/**
 * Item in *Footer → Company Links*
 */
export interface FooterDocumentDataCompanyLinksItem {
  /**
   * Label field in *Footer → Company Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.company_links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Link field in *Footer → Company Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.company_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Item in *Footer → Funding Links*
 */
export interface FooterDocumentDataFundingLinksItem {
  /**
   * Label field in *Footer → Funding Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.funding_links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Link field in *Footer → Funding Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.funding_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Item in *Footer → Support Links*
 */
export interface FooterDocumentDataSupportLinksItem {
  /**
   * Label field in *Footer → Support Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.support_links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Link field in *Footer → Support Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.support_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Item in *Footer → Policy Links*
 */
export interface FooterDocumentDataPolicyLinksItem {
  /**
   * Label field in *Footer → Policy Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.policy_links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Link field in *Footer → Policy Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.policy_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Company Title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.company_title
   * - **Tab**: Top
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_title: prismic.KeyTextField

  /**
   * Company Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.company_links[]
   * - **Tab**: Top
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  company_links: prismic.GroupField<
    Simplify<FooterDocumentDataCompanyLinksItem>
  >

  /**
   * Funding Title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.funding_title
   * - **Tab**: Top
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  funding_title: prismic.KeyTextField

  /**
   * Funding Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.funding_links[]
   * - **Tab**: Top
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  funding_links: prismic.GroupField<
    Simplify<FooterDocumentDataFundingLinksItem>
  >

  /**
   * Support Title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.support_title
   * - **Tab**: Top
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  support_title: prismic.KeyTextField

  /**
   * Support Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.support_links[]
   * - **Tab**: Top
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  support_links: prismic.GroupField<
    Simplify<FooterDocumentDataSupportLinksItem>
  >

  /**
   * Countries Title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.countries_title
   * - **Tab**: Top
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  countries_title: prismic.KeyTextField /**
   * FCA Statement field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.fca_statement
   * - **Tab**: Bottom
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  fca_statement: prismic.KeyTextField

  /**
   * Copyright field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.copyright
   * - **Tab**: Bottom
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright: prismic.KeyTextField

  /**
   * Policy Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.policy_links[]
   * - **Tab**: Bottom
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  policy_links: prismic.GroupField<Simplify<FooterDocumentDataPolicyLinksItem>>
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >

/**
 * Content for Global SEO documents
 */
interface GlobalSeoDocumentData {
  /**
   * Site Title field in *Global SEO*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: global_seo.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField

  /**
   * Meta Description field in *Global SEO*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: global_seo.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Open Graph Image field in *Global SEO*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: global_seo.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>
}

/**
 * Global SEO document from Prismic
 *
 * - **API ID**: `global_seo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalSeoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalSeoDocumentData>,
    "global_seo",
    Lang
  >

/**
 * Item in *Navbar → Navbar Left*
 */
export interface NavbarDocumentDataNavbarLeftItem {
  /**
   * Label field in *Navbar → Navbar Left*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navbar_left[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Link field in *Navbar → Navbar Left*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navbar_left[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Item in *Navbar → Navbar Right*
 */
export interface NavbarDocumentDataNavbarRightItem {
  /**
   * Label field in *Navbar → Navbar Right*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navbar_right[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Link field in *Navbar → Navbar Right*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navbar_right[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Content for Navbar documents
 */
interface NavbarDocumentData {
  /**
   * Navbar Left field in *Navbar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navbar_left[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navbar_left: prismic.GroupField<Simplify<NavbarDocumentDataNavbarLeftItem>>

  /**
   * Navbar Right field in *Navbar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navbar_right[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navbar_right: prismic.GroupField<Simplify<NavbarDocumentDataNavbarRightItem>>
}

/**
 * Navbar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavbarDocumentData>,
    "navbar",
    Lang
  >

type PageDocumentDataSlicesSlice =
  | BlogListAllSlice
  | CalloutSlice
  | FeaturedStoriesSlice
  | FeaturedBrandsSlice
  | FeaturedInSlice
  | ImageRightSlice
  | ProcessStepsSlice
  | UnmatchedServiceSlice
  | AboutUsSlice
  | PerfectFitSlice
  | UsingFundsSlice
  | FundingExplainedSlice
  | ScheduleCallSlice
  | PartnersSlice
  | BenefitsSlice
  | CalculatorSlice
  | TrustPilotStripSlice
  | ClientsSaySlice
  | HeroSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title (Browser Tab Title) field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Browser Tab Title
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title (Social Share Title) field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used when sharing on social media
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>

type SuccessStoryDocumentDataSlicesSlice =
  | CalloutSlice
  | ImageBlockSlice
  | SuccessStoryStatementsSlice
  | SuccessStoryHeroSlice
  | AboutUsSlice
  | BenefitsSlice
  | ImageRightSlice
  | PartnersSlice
  | HeroSlice
  | UnmatchedServiceSlice

/**
 * Content for Success Story Post documents
 */
interface SuccessStoryDocumentData {
  /**
   * Title (Browser Tab Title) field in *Success Story Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: success_story.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Heading field in *Success Story Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: success_story.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField

  /**
   * Brand Logo field in *Success Story Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: success_story.brand_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  brand_logo: prismic.ImageField<never>

  /**
   * Card Background Image field in *Success Story Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: success_story.card_background_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  card_background_image: prismic.ImageField<never>

  /**
   * Card Link Text field in *Success Story Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: success_story.card_link_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_link_text: prismic.KeyTextField

  /**
   * Cad Funded + Amount field in *Success Story Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: success_story.cad_funded_plus_amount
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cad_funded_plus_amount: prismic.KeyTextField

  /**
   * Slice Zone field in *Success Story Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: success_story.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SuccessStoryDocumentDataSlicesSlice> /**
   * Meta Title (Social Share Title) field in *Success Story Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: success_story.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Success Story Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: success_story.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Success Story Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: success_story.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Success Story Post document from Prismic
 *
 * - **API ID**: `success_story`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SuccessStoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SuccessStoryDocumentData>,
    "success_story",
    Lang
  >

/**
 * Content for Success Story Brand documents
 */
interface SuccessStoryBrandDocumentData {
  /**
   * Brand Name field in *Success Story Brand*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: success_story_brand.brand_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  brand_name: prismic.KeyTextField

  /**
   * Cad Funded + Amount field in *Success Story Brand*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: success_story_brand.cad_funded_plus_amount
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cad_funded_plus_amount: prismic.KeyTextField

  /**
   * Brand Logo field in *Success Story Brand*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: success_story_brand.brand_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  brand_logo: prismic.ImageField<never>

  /**
   * Card Background Image field in *Success Story Brand*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: success_story_brand.card_background_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  card_background_image: prismic.ImageField<never>
}

/**
 * Success Story Brand document from Prismic
 *
 * - **API ID**: `success_story_brand`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SuccessStoryBrandDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SuccessStoryBrandDocumentData>,
    "success_story_brand",
    Lang
  >

/**
 * Content for Testimonial documents
 */
interface TestimonialDocumentData {
  /**
   * Company Name field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.company_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name: prismic.KeyTextField

  /**
   * Company Logo field in *Testimonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.company_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  company_logo: prismic.ImageField<never>

  /**
   * Quote field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.quote
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  quote: prismic.KeyTextField

  /**
   * Name field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Job Title field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.job_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  job_title: prismic.KeyTextField

  /**
   * Profile photo field in *Testimonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.profile_photo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile_photo: prismic.ImageField<never>
}

/**
 * Testimonial document from Prismic
 *
 * - **API ID**: `testimonial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TestimonialDocumentData>,
    "testimonial",
    Lang
  >

export type AllDocumentTypes =
  | BlogPostDocument
  | FooterDocument
  | GlobalSeoDocument
  | NavbarDocument
  | PageDocument
  | SuccessStoryDocument
  | SuccessStoryBrandDocument
  | TestimonialDocument

/**
 * Primary content in *AboutUs → Primary*
 */
export interface AboutUsSliceDefaultPrimary {
  /**
   * Heading field in *AboutUs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField

  /**
   * Description field in *AboutUs → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField
}

/**
 * Primary content in *AboutUs → Items*
 */
export interface AboutUsSliceDefaultItem {
  /**
   * Text Top field in *AboutUs → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.items[].text_top
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_top: prismic.KeyTextField

  /**
   * Text Bottom field in *AboutUs → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.items[].text_bottom
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_bottom: prismic.KeyTextField
}

/**
 * Default variation for AboutUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutUsSliceDefaultPrimary>,
  Simplify<AboutUsSliceDefaultItem>
>

/**
 * Slice variation for *AboutUs*
 */
type AboutUsSliceVariation = AboutUsSliceDefault

/**
 * AboutUs Shared Slice
 *
 * - **API ID**: `about_us`
 * - **Description**: AboutUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsSlice = prismic.SharedSlice<
  "about_us",
  AboutUsSliceVariation
>

/**
 * Primary content in *Benefits → Items*
 */
export interface BenefitsSliceDefaultItem {
  /**
   * Top Text field in *Benefits → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.items[].top_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  top_text: prismic.KeyTextField

  /**
   * Bottom Text field in *Benefits → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.items[].bottom_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bottom_text: prismic.KeyTextField
}

/**
 * On Dark variation for Benefits Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BenefitsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<BenefitsSliceDefaultItem>
>

/**
 * Primary content in *Benefits → Items*
 */
export interface BenefitsSliceOnWhiteItem {
  /**
   * Top Text field in *Benefits → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.items[].top_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  top_text: prismic.KeyTextField

  /**
   * Bottom Text field in *Benefits → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.items[].bottom_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bottom_text: prismic.KeyTextField
}

/**
 * On White variation for Benefits Slice
 *
 * - **API ID**: `onWhite`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BenefitsSliceOnWhite = prismic.SharedSliceVariation<
  "onWhite",
  Record<string, never>,
  Simplify<BenefitsSliceOnWhiteItem>
>

/**
 * Slice variation for *Benefits*
 */
type BenefitsSliceVariation = BenefitsSliceDefault | BenefitsSliceOnWhite

/**
 * Benefits Shared Slice
 *
 * - **API ID**: `benefits`
 * - **Description**: Benefits
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BenefitsSlice = prismic.SharedSlice<
  "benefits",
  BenefitsSliceVariation
>

/**
 * Default variation for BlogListAll Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogListAllSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>

/**
 * Slice variation for *BlogListAll*
 */
type BlogListAllSliceVariation = BlogListAllSliceDefault

/**
 * BlogListAll Shared Slice
 *
 * - **API ID**: `blog_list_all`
 * - **Description**: BlogListAll
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogListAllSlice = prismic.SharedSlice<
  "blog_list_all",
  BlogListAllSliceVariation
>

/**
 * Primary content in *BlogPostBody → Primary*
 */
export interface BlogPostBodySliceDefaultPrimary {
  /**
   * Body field in *BlogPostBody → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_body.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField
}

/**
 * Default variation for BlogPostBody Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostBodySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogPostBodySliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *BlogPostBody*
 */
type BlogPostBodySliceVariation = BlogPostBodySliceDefault

/**
 * BlogPostBody Shared Slice
 *
 * - **API ID**: `blog_post_body`
 * - **Description**: BlogPostBody
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostBodySlice = prismic.SharedSlice<
  "blog_post_body",
  BlogPostBodySliceVariation
>

/**
 * Primary content in *Calculator → Primary*
 */
export interface CalculatorSliceDefaultPrimary {
  /**
   * Heading field in *Calculator → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calculator.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField

  /**
   * Description field in *Calculator → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calculator.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Subheading field in *Calculator → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calculator.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField

  /**
   * Currency field in *Calculator → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: calculator.primary.currency
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  currency: prismic.SelectField<"GBP" | "EUR" | "USD" | "AUD">

  /**
   * Amount Title field in *Calculator → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calculator.primary.amount_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  amount_title: prismic.KeyTextField

  /**
   * Amounts field in *Calculator → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Amounts separated by comma like: 10000, 25000, 50000
   * - **API ID Path**: calculator.primary.amounts
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  amounts: prismic.KeyTextField

  /**
   * Fees field in *Calculator → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Put is the same number of fees as there are term option
   * - **API ID Path**: calculator.primary.fees
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  fees: prismic.KeyTextField

  /**
   * Term Title field in *Calculator → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calculator.primary.term_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  term_title: prismic.KeyTextField

  /**
   * Term Min (Months) field in *Calculator → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: calculator.primary.term_min
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  term_min: prismic.NumberField

  /**
   * Term Max (Months) field in *Calculator → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: calculator.primary.term_max
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  term_max: prismic.NumberField

  /**
   * Slider Months Text field in *Calculator → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calculator.primary.slider_months_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slider_months_text: prismic.KeyTextField

  /**
   * Total Title field in *Calculator → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calculator.primary.total_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  total_title: prismic.KeyTextField

  /**
   * Button Text field in *Calculator → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calculator.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField

  /**
   * Button Note field in *Calculator → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calculator.primary.button_note
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_note: prismic.KeyTextField
}

/**
 * Primary content in *Calculator → Items*
 */
export interface CalculatorSliceDefaultItem {
  /**
   * Bulletpoint field in *Calculator → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calculator.items[].bulletpoint
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bulletpoint: prismic.KeyTextField
}

/**
 * Default variation for Calculator Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalculatorSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CalculatorSliceDefaultPrimary>,
  Simplify<CalculatorSliceDefaultItem>
>

/**
 * Slice variation for *Calculator*
 */
type CalculatorSliceVariation = CalculatorSliceDefault

/**
 * Calculator Shared Slice
 *
 * - **API ID**: `calculator`
 * - **Description**: Calculator
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalculatorSlice = prismic.SharedSlice<
  "calculator",
  CalculatorSliceVariation
>

/**
 * Primary content in *Callout → Primary*
 */
export interface CalloutSliceDefaultPrimary {
  /**
   * Title field in *Callout → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Button Text field in *Callout → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField
}

/**
 * Default variation for Callout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalloutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CalloutSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *Callout → Primary*
 */
export interface CalloutSliceForBlogPagePrimary {
  /**
   * Title field in *Callout → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Button Text field in *Callout → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField
}

/**
 * For Blog page variation for Callout Slice
 *
 * - **API ID**: `forBlogPage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalloutSliceForBlogPage = prismic.SharedSliceVariation<
  "forBlogPage",
  Simplify<CalloutSliceForBlogPagePrimary>,
  never
>

/**
 * Slice variation for *Callout*
 */
type CalloutSliceVariation = CalloutSliceDefault | CalloutSliceForBlogPage

/**
 * Callout Shared Slice
 *
 * - **API ID**: `callout`
 * - **Description**: Callout
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalloutSlice = prismic.SharedSlice<"callout", CalloutSliceVariation>

/**
 * Primary content in *ClientsSay → Primary*
 */
export interface ClientsSaySliceDefaultPrimary {
  /**
   * Heading field in *ClientsSay → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clients_say.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField

  /**
   * CTA Title field in *ClientsSay → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clients_say.primary.cta_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_title: prismic.KeyTextField

  /**
   * Button Text field in *ClientsSay → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clients_say.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField
}

/**
 * Primary content in *ClientsSay → Items*
 */
export interface ClientsSaySliceDefaultItem {
  /**
   * Testimonial field in *ClientsSay → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: clients_say.items[].testimonial
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  testimonial: prismic.ContentRelationshipField<"testimonial">
}

/**
 * Default variation for ClientsSay Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientsSaySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ClientsSaySliceDefaultPrimary>,
  Simplify<ClientsSaySliceDefaultItem>
>

/**
 * Slice variation for *ClientsSay*
 */
type ClientsSaySliceVariation = ClientsSaySliceDefault

/**
 * ClientsSay Shared Slice
 *
 * - **API ID**: `clients_say`
 * - **Description**: ClientsSay
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientsSaySlice = prismic.SharedSlice<
  "clients_say",
  ClientsSaySliceVariation
>

/**
 * Primary content in *FeaturedBrands → Primary*
 */
export interface FeaturedBrandsSliceDefaultPrimary {
  /**
   * Heading field in *FeaturedBrands → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_brands.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField

  /**
   * Final Box Title field in *FeaturedBrands → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_brands.primary.final_box_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  final_box_title: prismic.KeyTextField

  /**
   * Button Text field in *FeaturedBrands → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_brands.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField
}

/**
 * Primary content in *FeaturedBrands → Items*
 */
export interface FeaturedBrandsSliceDefaultItem {
  /**
   * Brand field in *FeaturedBrands → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_brands.items[].brand
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  brand: prismic.ContentRelationshipField<"success_story_brand">
}

/**
 * Default variation for FeaturedBrands Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedBrandsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedBrandsSliceDefaultPrimary>,
  Simplify<FeaturedBrandsSliceDefaultItem>
>

/**
 * Slice variation for *FeaturedBrands*
 */
type FeaturedBrandsSliceVariation = FeaturedBrandsSliceDefault

/**
 * FeaturedBrands Shared Slice
 *
 * - **API ID**: `featured_brands`
 * - **Description**: FeaturedBrands
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedBrandsSlice = prismic.SharedSlice<
  "featured_brands",
  FeaturedBrandsSliceVariation
>

/**
 * Primary content in *FeaturedIn → Primary*
 */
export interface FeaturedInSliceDefaultPrimary {
  /**
   * Heading field in *FeaturedIn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_in.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField
}

/**
 * Primary content in *FeaturedIn → Items*
 */
export interface FeaturedInSliceDefaultItem {
  /**
   * Tag field in *FeaturedIn → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_in.items[].tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField

  /**
   * Description field in *FeaturedIn → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_in.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Logo field in *FeaturedIn → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_in.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>

  /**
   * URL field in *FeaturedIn → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_in.items[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField
}

/**
 * Default variation for FeaturedIn Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedInSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedInSliceDefaultPrimary>,
  Simplify<FeaturedInSliceDefaultItem>
>

/**
 * Slice variation for *FeaturedIn*
 */
type FeaturedInSliceVariation = FeaturedInSliceDefault

/**
 * FeaturedIn Shared Slice
 *
 * - **API ID**: `featured_in`
 * - **Description**: FeaturedIn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedInSlice = prismic.SharedSlice<
  "featured_in",
  FeaturedInSliceVariation
>

/**
 * Primary content in *FeaturedStories → Primary*
 */
export interface FeaturedStoriesSliceDefaultPrimary {
  /**
   * Heading field in *FeaturedStories → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_stories.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField
}

/**
 * Primary content in *FeaturedStories → Items*
 */
export interface FeaturedStoriesSliceDefaultItem {
  /**
   * Featured Story field in *FeaturedStories → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_stories.items[].featured_story
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  featured_story: prismic.ContentRelationshipField<"success_story">
}

/**
 * Default variation for FeaturedStories Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedStoriesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedStoriesSliceDefaultPrimary>,
  Simplify<FeaturedStoriesSliceDefaultItem>
>

/**
 * Slice variation for *FeaturedStories*
 */
type FeaturedStoriesSliceVariation = FeaturedStoriesSliceDefault

/**
 * FeaturedStories Shared Slice
 *
 * - **API ID**: `featured_stories`
 * - **Description**: FeaturedStories
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedStoriesSlice = prismic.SharedSlice<
  "featured_stories",
  FeaturedStoriesSliceVariation
>

/**
 * Primary content in *FundingExplained → Primary*
 */
export interface FundingExplainedSliceDefaultPrimary {
  /**
   * Heading field in *FundingExplained → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: funding_explained.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField
}

/**
 * Primary content in *FundingExplained → Items*
 */
export interface FundingExplainedSliceDefaultItem {
  /**
   * Title field in *FundingExplained → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: funding_explained.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Description field in *FundingExplained → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: funding_explained.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Icon field in *FundingExplained → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: funding_explained.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>
}

/**
 * Default variation for FundingExplained Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FundingExplainedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FundingExplainedSliceDefaultPrimary>,
  Simplify<FundingExplainedSliceDefaultItem>
>

/**
 * Slice variation for *FundingExplained*
 */
type FundingExplainedSliceVariation = FundingExplainedSliceDefault

/**
 * FundingExplained Shared Slice
 *
 * - **API ID**: `funding_explained`
 * - **Description**: FundingExplained
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FundingExplainedSlice = prismic.SharedSlice<
  "funding_explained",
  FundingExplainedSliceVariation
>

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField

  /**
   * Description field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Button Text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField

  /**
   * Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"mobile">

  /**
   * Button Note field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_note
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_note: prismic.KeyTextField
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceSimplePrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Description field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField
}

/**
 * Simple variation for Hero Slice
 *
 * - **API ID**: `simple`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSimple = prismic.SharedSliceVariation<
  "simple",
  Simplify<HeroSliceSimplePrimary>,
  never
>

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceBlogPostPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Blog Post variation for Hero Slice
 *
 * - **API ID**: `blogPost`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceBlogPost = prismic.SharedSliceVariation<
  "blogPost",
  Simplify<HeroSliceBlogPostPrimary>,
  never
>

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceSimple | HeroSliceBlogPost

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>

/**
 * Primary content in *ImageBlock → Primary*
 */
export interface ImageBlockSliceDefaultPrimary {
  /**
   * Left Image field in *ImageBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_block.primary.left_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  left_image: prismic.ImageField<never>

  /**
   * Right Image field in *ImageBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_block.primary.right_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  right_image: prismic.ImageField<never>
}

/**
 * Default variation for ImageBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageBlockSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *ImageBlock*
 */
type ImageBlockSliceVariation = ImageBlockSliceDefault

/**
 * ImageBlock Shared Slice
 *
 * - **API ID**: `image_block`
 * - **Description**: ImageBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBlockSlice = prismic.SharedSlice<
  "image_block",
  ImageBlockSliceVariation
>

/**
 * Primary content in *ImageRight → Primary*
 */
export interface ImageRightSliceDefaultPrimary {
  /**
   * Heading field in *ImageRight → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_right.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField

  /**
   * Description field in *ImageRight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_right.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Image field in *ImageRight → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_right.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Button Text field in *ImageRight → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_right.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField
}

/**
 * Default variation for ImageRight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageRightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageRightSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *ImageRight*
 */
type ImageRightSliceVariation = ImageRightSliceDefault

/**
 * ImageRight Shared Slice
 *
 * - **API ID**: `image_right`
 * - **Description**: ImageRight
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageRightSlice = prismic.SharedSlice<
  "image_right",
  ImageRightSliceVariation
>

/**
 * Primary content in *Partners → Primary*
 */
export interface PartnersSliceDefaultPrimary {
  /**
   * Heading field in *Partners → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField

  /**
   * Description field in *Partners → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField
}

/**
 * Primary content in *Partners → Items*
 */
export interface PartnersSliceDefaultItem {
  /**
   * Partner Logo field in *Partners → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.items[].partner_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  partner_logo: prismic.ImageField<never>
}

/**
 * Default variation for Partners Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PartnersSliceDefaultPrimary>,
  Simplify<PartnersSliceDefaultItem>
>

/**
 * Slice variation for *Partners*
 */
type PartnersSliceVariation = PartnersSliceDefault

/**
 * Partners Shared Slice
 *
 * - **API ID**: `partners`
 * - **Description**: Partners
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnersSlice = prismic.SharedSlice<
  "partners",
  PartnersSliceVariation
>

/**
 * Primary content in *PerfectFit → Primary*
 */
export interface PerfectFitSliceDefaultPrimary {
  /**
   * Heading field in *PerfectFit → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: perfect_fit.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField

  /**
   * Description field in *PerfectFit → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: perfect_fit.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Button Text field in *PerfectFit → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: perfect_fit.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField
}

/**
 * Primary content in *PerfectFit → Items*
 */
export interface PerfectFitSliceDefaultItem {
  /**
   * Column1 field in *PerfectFit → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: perfect_fit.items[].column1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  column1: prismic.KeyTextField

  /**
   * Column2 field in *PerfectFit → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: perfect_fit.items[].column2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  column2: prismic.KeyTextField

  /**
   * Column3 field in *PerfectFit → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: perfect_fit.items[].column3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  column3: prismic.KeyTextField

  /**
   * Column4 field in *PerfectFit → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: perfect_fit.items[].column4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  column4: prismic.KeyTextField
}

/**
 * Default variation for PerfectFit Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PerfectFitSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PerfectFitSliceDefaultPrimary>,
  Simplify<PerfectFitSliceDefaultItem>
>

/**
 * Slice variation for *PerfectFit*
 */
type PerfectFitSliceVariation = PerfectFitSliceDefault

/**
 * PerfectFit Shared Slice
 *
 * - **API ID**: `perfect_fit`
 * - **Description**: PerfectFit
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PerfectFitSlice = prismic.SharedSlice<
  "perfect_fit",
  PerfectFitSliceVariation
>

/**
 * Primary content in *ProcessSteps → Primary*
 */
export interface ProcessStepsSliceDefaultPrimary {
  /**
   * Heading field in *ProcessSteps → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField

  /**
   * Description field in *ProcessSteps → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField

  /**
   * Start Supercharging Title field in *ProcessSteps → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.primary.start_supercharging_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  start_supercharging_title: prismic.KeyTextField

  /**
   * Button Text field in *ProcessSteps → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField
}

/**
 * Primary content in *ProcessSteps → Items*
 */
export interface ProcessStepsSliceDefaultItem {
  /**
   * Title field in *ProcessSteps → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Description field in *ProcessSteps → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField
}

/**
 * Default variation for ProcessSteps Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProcessStepsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProcessStepsSliceDefaultPrimary>,
  Simplify<ProcessStepsSliceDefaultItem>
>

/**
 * Slice variation for *ProcessSteps*
 */
type ProcessStepsSliceVariation = ProcessStepsSliceDefault

/**
 * ProcessSteps Shared Slice
 *
 * - **API ID**: `process_steps`
 * - **Description**: ProcessSteps
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProcessStepsSlice = prismic.SharedSlice<
  "process_steps",
  ProcessStepsSliceVariation
>

/**
 * Primary content in *ScheduleCall → Primary*
 */
export interface ScheduleCallSliceDefaultPrimary {
  /**
   * Title field in *ScheduleCall → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule_call.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Description field in *ScheduleCall → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule_call.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField

  /**
   * Button Text field in *ScheduleCall → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule_call.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField

  /**
   * Button Link field in *ScheduleCall → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule_call.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField

  /**
   * Image field in *ScheduleCall → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule_call.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Default variation for ScheduleCall Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScheduleCallSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ScheduleCallSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *ScheduleCall*
 */
type ScheduleCallSliceVariation = ScheduleCallSliceDefault

/**
 * ScheduleCall Shared Slice
 *
 * - **API ID**: `schedule_call`
 * - **Description**: ScheduleCall
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScheduleCallSlice = prismic.SharedSlice<
  "schedule_call",
  ScheduleCallSliceVariation
>

/**
 * Primary content in *SuccessStoryHero → Primary*
 */
export interface SuccessStoryHeroSliceDefaultPrimary {
  /**
   * Heading field in *SuccessStoryHero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: success_story_hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField

  /**
   * Text field in *SuccessStoryHero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: success_story_hero.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * Founder Image field in *SuccessStoryHero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: success_story_hero.primary.founder_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  founder_image: prismic.ImageField<never>

  /**
   * Founder Name field in *SuccessStoryHero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: success_story_hero.primary.founder_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  founder_name: prismic.KeyTextField

  /**
   * Founder Title field in *SuccessStoryHero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: success_story_hero.primary.founder_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  founder_title: prismic.KeyTextField
}

/**
 * Default variation for SuccessStoryHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SuccessStoryHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SuccessStoryHeroSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *SuccessStoryHero*
 */
type SuccessStoryHeroSliceVariation = SuccessStoryHeroSliceDefault

/**
 * SuccessStoryHero Shared Slice
 *
 * - **API ID**: `success_story_hero`
 * - **Description**: SuccessStoryHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SuccessStoryHeroSlice = prismic.SharedSlice<
  "success_story_hero",
  SuccessStoryHeroSliceVariation
>

/**
 * Primary content in *SuccessStoryStatements → Primary*
 */
export interface SuccessStoryStatementsSliceDefaultPrimary {
  /**
   * Quote field in *SuccessStoryStatements → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: success_story_statements.primary.quote
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  quote: prismic.KeyTextField

  /**
   * Quote By field in *SuccessStoryStatements → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: success_story_statements.primary.quote_by
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  quote_by: prismic.KeyTextField
}

/**
 * Primary content in *SuccessStoryStatements → Items*
 */
export interface SuccessStoryStatementsSliceDefaultItem {
  /**
   * Title field in *SuccessStoryStatements → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: success_story_statements.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Description field in *SuccessStoryStatements → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: success_story_statements.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField
}

/**
 * Default variation for SuccessStoryStatements Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SuccessStoryStatementsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SuccessStoryStatementsSliceDefaultPrimary>,
  Simplify<SuccessStoryStatementsSliceDefaultItem>
>

/**
 * Slice variation for *SuccessStoryStatements*
 */
type SuccessStoryStatementsSliceVariation = SuccessStoryStatementsSliceDefault

/**
 * SuccessStoryStatements Shared Slice
 *
 * - **API ID**: `success_story_statements`
 * - **Description**: SuccessStoryStatements
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SuccessStoryStatementsSlice = prismic.SharedSlice<
  "success_story_statements",
  SuccessStoryStatementsSliceVariation
>

/**
 * Primary content in *TrustPilotStrip → Items*
 */
export interface TrustPilotStripSliceDefaultItem {
  /**
   * title field in *TrustPilotStrip → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trust_pilot_strip.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * review field in *TrustPilotStrip → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trust_pilot_strip.items[].review
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  review: prismic.KeyTextField

  /**
   * name field in *TrustPilotStrip → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trust_pilot_strip.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * date field in *TrustPilotStrip → Items*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: trust_pilot_strip.items[].date
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  date: prismic.TimestampField

  /**
   * url field in *TrustPilotStrip → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trust_pilot_strip.items[].url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  url: prismic.KeyTextField
}

/**
 * Default variation for TrustPilotStrip Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TrustPilotStripSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<TrustPilotStripSliceDefaultItem>
>

/**
 * Slice variation for *TrustPilotStrip*
 */
type TrustPilotStripSliceVariation = TrustPilotStripSliceDefault

/**
 * TrustPilotStrip Shared Slice
 *
 * - **API ID**: `trust_pilot_strip`
 * - **Description**: TrustPilotStrip
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TrustPilotStripSlice = prismic.SharedSlice<
  "trust_pilot_strip",
  TrustPilotStripSliceVariation
>

/**
 * Primary content in *ThreeColumns → Primary*
 */
export interface UnmatchedServiceSliceDefaultPrimary {
  /**
   * Heading field in *ThreeColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: unmatched_service.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField
}

/**
 * Primary content in *ThreeColumns → Items*
 */
export interface UnmatchedServiceSliceDefaultItem {
  /**
   * Title field in *ThreeColumns → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: unmatched_service.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Icon field in *ThreeColumns → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: unmatched_service.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>

  /**
   * Description field in *ThreeColumns → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: unmatched_service.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField
}

/**
 * Default variation for ThreeColumns Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UnmatchedServiceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<UnmatchedServiceSliceDefaultPrimary>,
  Simplify<UnmatchedServiceSliceDefaultItem>
>

/**
 * Primary content in *ThreeColumns → Primary*
 */
export interface UnmatchedServiceSliceWideWithDescriptionPrimary {
  /**
   * Heading field in *ThreeColumns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: unmatched_service.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField

  /**
   * Description field in *ThreeColumns → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: unmatched_service.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField
}

/**
 * Primary content in *ThreeColumns → Items*
 */
export interface UnmatchedServiceSliceWideWithDescriptionItem {
  /**
   * Title field in *ThreeColumns → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: unmatched_service.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Icon field in *ThreeColumns → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: unmatched_service.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>

  /**
   * Description field in *ThreeColumns → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: unmatched_service.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField
}

/**
 * Wide - With description variation for ThreeColumns Slice
 *
 * - **API ID**: `wideWithDescription`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UnmatchedServiceSliceWideWithDescription =
  prismic.SharedSliceVariation<
    "wideWithDescription",
    Simplify<UnmatchedServiceSliceWideWithDescriptionPrimary>,
    Simplify<UnmatchedServiceSliceWideWithDescriptionItem>
  >

/**
 * Slice variation for *ThreeColumns*
 */
type UnmatchedServiceSliceVariation =
  | UnmatchedServiceSliceDefault
  | UnmatchedServiceSliceWideWithDescription

/**
 * ThreeColumns Shared Slice
 *
 * - **API ID**: `unmatched_service`
 * - **Description**: UnmatchedService
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UnmatchedServiceSlice = prismic.SharedSlice<
  "unmatched_service",
  UnmatchedServiceSliceVariation
>

/**
 * Primary content in *UsingFunds → Primary*
 */
export interface UsingFundsSliceDefaultPrimary {
  /**
   * Heading field in *UsingFunds → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: using_funds.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField
}

/**
 * Primary content in *UsingFunds → Items*
 */
export interface UsingFundsSliceDefaultItem {
  /**
   * Icon field in *UsingFunds → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: using_funds.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>

  /**
   * Title field in *UsingFunds → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: using_funds.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Description field in *UsingFunds → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: using_funds.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField
}

/**
 * Default variation for UsingFunds Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UsingFundsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<UsingFundsSliceDefaultPrimary>,
  Simplify<UsingFundsSliceDefaultItem>
>

/**
 * Slice variation for *UsingFunds*
 */
type UsingFundsSliceVariation = UsingFundsSliceDefault

/**
 * UsingFunds Shared Slice
 *
 * - **API ID**: `using_funds`
 * - **Description**: UsingFunds
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UsingFundsSlice = prismic.SharedSlice<
  "using_funds",
  UsingFundsSliceVariation
>

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataCompanyLinksItem,
      FooterDocumentDataFundingLinksItem,
      FooterDocumentDataSupportLinksItem,
      FooterDocumentDataPolicyLinksItem,
      GlobalSeoDocument,
      GlobalSeoDocumentData,
      NavbarDocument,
      NavbarDocumentData,
      NavbarDocumentDataNavbarLeftItem,
      NavbarDocumentDataNavbarRightItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SuccessStoryDocument,
      SuccessStoryDocumentData,
      SuccessStoryDocumentDataSlicesSlice,
      SuccessStoryBrandDocument,
      SuccessStoryBrandDocumentData,
      TestimonialDocument,
      TestimonialDocumentData,
      AllDocumentTypes,
      AboutUsSlice,
      AboutUsSliceDefaultPrimary,
      AboutUsSliceDefaultItem,
      AboutUsSliceVariation,
      AboutUsSliceDefault,
      BenefitsSlice,
      BenefitsSliceDefaultItem,
      BenefitsSliceOnWhiteItem,
      BenefitsSliceVariation,
      BenefitsSliceDefault,
      BenefitsSliceOnWhite,
      BlogListAllSlice,
      BlogListAllSliceVariation,
      BlogListAllSliceDefault,
      BlogPostBodySlice,
      BlogPostBodySliceDefaultPrimary,
      BlogPostBodySliceVariation,
      BlogPostBodySliceDefault,
      CalculatorSlice,
      CalculatorSliceDefaultPrimary,
      CalculatorSliceDefaultItem,
      CalculatorSliceVariation,
      CalculatorSliceDefault,
      CalloutSlice,
      CalloutSliceDefaultPrimary,
      CalloutSliceForBlogPagePrimary,
      CalloutSliceVariation,
      CalloutSliceDefault,
      CalloutSliceForBlogPage,
      ClientsSaySlice,
      ClientsSaySliceDefaultPrimary,
      ClientsSaySliceDefaultItem,
      ClientsSaySliceVariation,
      ClientsSaySliceDefault,
      FeaturedBrandsSlice,
      FeaturedBrandsSliceDefaultPrimary,
      FeaturedBrandsSliceDefaultItem,
      FeaturedBrandsSliceVariation,
      FeaturedBrandsSliceDefault,
      FeaturedInSlice,
      FeaturedInSliceDefaultPrimary,
      FeaturedInSliceDefaultItem,
      FeaturedInSliceVariation,
      FeaturedInSliceDefault,
      FeaturedStoriesSlice,
      FeaturedStoriesSliceDefaultPrimary,
      FeaturedStoriesSliceDefaultItem,
      FeaturedStoriesSliceVariation,
      FeaturedStoriesSliceDefault,
      FundingExplainedSlice,
      FundingExplainedSliceDefaultPrimary,
      FundingExplainedSliceDefaultItem,
      FundingExplainedSliceVariation,
      FundingExplainedSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceSimplePrimary,
      HeroSliceBlogPostPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceSimple,
      HeroSliceBlogPost,
      ImageBlockSlice,
      ImageBlockSliceDefaultPrimary,
      ImageBlockSliceVariation,
      ImageBlockSliceDefault,
      ImageRightSlice,
      ImageRightSliceDefaultPrimary,
      ImageRightSliceVariation,
      ImageRightSliceDefault,
      PartnersSlice,
      PartnersSliceDefaultPrimary,
      PartnersSliceDefaultItem,
      PartnersSliceVariation,
      PartnersSliceDefault,
      PerfectFitSlice,
      PerfectFitSliceDefaultPrimary,
      PerfectFitSliceDefaultItem,
      PerfectFitSliceVariation,
      PerfectFitSliceDefault,
      ProcessStepsSlice,
      ProcessStepsSliceDefaultPrimary,
      ProcessStepsSliceDefaultItem,
      ProcessStepsSliceVariation,
      ProcessStepsSliceDefault,
      ScheduleCallSlice,
      ScheduleCallSliceDefaultPrimary,
      ScheduleCallSliceVariation,
      ScheduleCallSliceDefault,
      SuccessStoryHeroSlice,
      SuccessStoryHeroSliceDefaultPrimary,
      SuccessStoryHeroSliceVariation,
      SuccessStoryHeroSliceDefault,
      SuccessStoryStatementsSlice,
      SuccessStoryStatementsSliceDefaultPrimary,
      SuccessStoryStatementsSliceDefaultItem,
      SuccessStoryStatementsSliceVariation,
      SuccessStoryStatementsSliceDefault,
      TrustPilotStripSlice,
      TrustPilotStripSliceDefaultItem,
      TrustPilotStripSliceVariation,
      TrustPilotStripSliceDefault,
      UnmatchedServiceSlice,
      UnmatchedServiceSliceDefaultPrimary,
      UnmatchedServiceSliceDefaultItem,
      UnmatchedServiceSliceWideWithDescriptionPrimary,
      UnmatchedServiceSliceWideWithDescriptionItem,
      UnmatchedServiceSliceVariation,
      UnmatchedServiceSliceDefault,
      UnmatchedServiceSliceWideWithDescription,
      UsingFundsSlice,
      UsingFundsSliceDefaultPrimary,
      UsingFundsSliceDefaultItem,
      UsingFundsSliceVariation,
      UsingFundsSliceDefault,
    }
  }
}
