// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic"

export const components = {
  about_us: dynamic(() => import("./AboutUs")),
  benefits: dynamic(() => import("./Benefits")),
  calculator: dynamic(() => import("./Calculator")),
  clients_say: dynamic(() => import("./ClientsSay")),
  funding_explained: dynamic(() => import("./FundingExplained")),
  hero: dynamic(() => import("./Hero")),
  partners: dynamic(() => import("./Partners")),
  perfect_fit: dynamic(() => import("./PerfectFit")),
  process_steps: dynamic(() => import("./ProcessSteps")),
  schedule_call: dynamic(() => import("./ScheduleCall")),
  trust_pilot_strip: dynamic(() => import("./TrustPilotStrip")),
  unmatched_service: dynamic(() => import("./ThreeColumns")),
  using_funds: dynamic(() => import("./UsingFunds")),
}
