// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic"

export const components = {
  benefits: dynamic(() => import("./Benefits")),
  business_benefits: dynamic(() => import("./BusinessBenefits")),
  calculator: dynamic(() => import("./Calculator")),
  clients_say: dynamic(() => import("./ClientsSay")),
  funding_explained: dynamic(() => import("./FundingExplained")),
  funding_types: dynamic(() => import("./FundingTypes")),
  hero: dynamic(() => import("./Hero")),
  partners: dynamic(() => import("./Partners")),
  perfect_fit: dynamic(() => import("./PerfectFit")),
  schedule_call: dynamic(() => import("./ScheduleCall")),
  trust_pilot_strip: dynamic(() => import("./TrustPilotStrip")),
  using_funds: dynamic(() => import("./UsingFunds")),
}
