// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic"

export const components = {
  about_us: dynamic(() => import("./AboutUs")),
  benefits: dynamic(() => import("./Benefits")),
  blog_post_body: dynamic(() => import("./BlogPostBody")),
  calculator: dynamic(() => import("./Calculator")),
  callout: dynamic(() => import("./Callout")),
  check_list: dynamic(() => import("./CheckList")),
  clients_say: dynamic(() => import("./ClientsSay")),
  contact_us: dynamic(() => import("./ContactUs")),
  featured_brands: dynamic(() => import("./FeaturedBrands")),
  featured_in: dynamic(() => import("./FeaturedIn")),
  featured_stories: dynamic(() => import("./FeaturedStories")),
  flex_hero: dynamic(() => import("./FlexHero")),
  funding_explained: dynamic(() => import("./FundingExplained")),
  hero: dynamic(() => import("./Hero")),
  image_block: dynamic(() => import("./ImageBlock")),
  image_right: dynamic(() => import("./ImageRight")),
  partners: dynamic(() => import("./Partners")),
  perfect_fit: dynamic(() => import("./PerfectFit")),
  process_steps: dynamic(() => import("./ProcessSteps")),
  schedule_call: dynamic(() => import("./ScheduleCall")),
  success_story_hero: dynamic(() => import("./SuccessStoryHero")),
  success_story_statements: dynamic(() => import("./SuccessStoryStatements")),
  trust_pilot_strip: dynamic(() => import("./TrustPilotStrip")),
  unmatched_service: dynamic(() => import("./ThreeColumns")),
  using_funds: dynamic(() => import("./UsingFunds")),
}
